package enums;

public enum Major {
    AUTOMATICS_AND_APPLIED_INFORMATICS, COMMUNICATION_AND_PUBLIC_RELATIONS, COMPUTER_SCIENCE,
    HORTICULTURAL_ENGINEERING, INFORMATION_SERVICE, LANDSCAPE_ARCHITECTURE, MANUFACTURING_ENGINEERING,
    MECHATRONICS, PUBLIC_HEALTH_SERVICES_AND_POLICIES, TELECOMMUNICATION, TRANSLATION_AND_INTERPRETING_STUDIES;

    private int creditNumber;
    private String courseID;
}
